FPR_start_epoch: 0
FPR_stop_epoch: 60
PR_weight: 0.00015
RC_use_FP: false
RC_use_both: false
RC_weight: 0.12
aa: rand-m9-mstd0.5-inc1
attention_dir: null
attention_type: fused
batch_size: 64
cam_npy_dir: null
clip_grad: null
cluster_data_list: train_aug_id.txt
color_jitter: 0.4
cooldown_epochs: 10
data_path: ./dataset/20220311_8bit_24ver
data_set: landslide
decay_epochs: 30
decay_rate: 0.1
device: cuda
drop: 0.0
drop_path: 0.1
epochs: 60
eval: false
eval_miou_threshold_end: 60
eval_miou_threshold_start: 35
finetune: https://dl.fbaipublicfiles.com/deit/deit_small_patch16_224-cd65a155.pth
gen_all_prototypes: false
gen_attention_maps: false
gen_prototypes_threshold: 0.5
gt_dir: SegmentationClass
high_alpha: 12
if_eval_miou: true
image_ch: 3
img_list: train_id.txt
input_size: 224
label_file_path: null
layer_index: 12
low_alpha: 1
lr: 0.0005
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mask_thresh: 0.45
min_lr: 1.0e-05
model: deit_small_MCTformerV2_patch16_224
momentum: 0.9
no_return_fine: true
no_visualize_cls_attn: true
num_cluster: 10
num_workers: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
out_crf: null
output_dir: ''
patch_attn_refine: true
patch_size: 16
patience_epochs: 10
pin_mem: true
prototypes_FP_use_patch: false
prototypes_TP_use_patch: false
prototypes_dir: null
prototypes_knum: 1
prototypes_start_epoch: 0
prototypes_use_only_FP: false
prototypes_use_only_TP: false
prototypes_weight: 0.12
recount: 1
remode: pixel
repeated_aug: true
reprob: 0.25
resplit: false
resume: ''
return_fine: true
save_all_prototypes: false
save_break: 0
scales:
- 1.0
sched: cosine
seed: 0
smoothing: 0.1
start_epoch: 0
tempt: 13
train_interpolation: bicubic
use_FPR: true
use_prototypes: false
visualize_cls_attn: true
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 0.05
